name: Fields-Service Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build fields-service
        run: docker-compose up -d
      - name: Logs
        run: docker-compose logs
      - name: Service logs
        run: docker logs fields-back
